image:
  file: Dockerfile
tasks:
- command: >
    cd examples/hello_world/ &&
    flutter packages pub global activate webdev &&
    flutter packages upgrade && pub get &&
    webdev serve
ports:
- port: 8080
vscode:
  extensions:
    - Dart-Code.flutter@3.0.2:nbR3uuzoFf6luWQnrRXSeQ==
    - Dart-Code.dart-code@3.0.2:o7Ao4CJ44j6ZOBBljm/Q8w==